apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-deploy
  labels:
    app: config-server-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server-deploy
  template:
    metadata:
      labels:
        app: config-server-deploy
    spec:
      containers:
        - env:
          - name: SPRING_CLOUD_CONFIG_SERVER_GIT_URI
            value: https://github.com/residencia2020ito/config
          name: config-server
          image: hyness/spring-cloud-config-server
          ports:
          - containerPort: 8080
            protocol: TCP
