apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-deploy
  labels:
    app: config-server-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: config-server-deploy
  template:
    metadata:
      labels:
        app: config-server-deploy
    spec:
      dnsPolicy: Default
      restartPolicy: Always
      containers:
        - env:
          - name: SPRING_CLOUD_CONFIG_SERVER_GIT_URI
            value: https://github.com/residencia2020ito/config
          - name: SPRING_CLOUD_CONFIG_SERVER_GIT_SKIPSSLVALIDATION
            value: 'true'
          name: config-server
          image: hyness/spring-cloud-config-server
          ports:
          - containerPort: 8888
            protocol: TCP
