apiVersion: v1
kind: Service
metadata:
  name: config-server-service
  labels:
    run: config-server-service
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8888
  selector:
    app: config-server-deploy
