apiVersion: v1
kind: Service
metadata:
  name: conf-server-service
  labels:
    run: conf-server-service
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8888
  selector:
    app: conf-server-deploy