apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: devops-demo-ci
  namespace: devops
  labels:
    app: demp-ci
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  rules:
  - host: devops-demo-ci.yoconsumo.municipiodeoaxaca.gob.mx
    http:
      paths:
      - path: /
        backend:
          serviceName: devops-demo-ci
          servicePort: 80
  tls:
  -  secretName: secure-tls
     hosts:
     - devops-demo-ci.yoconsumo.municipiodeoaxaca.gob.mx
