apiVersion: v1
kind: Service
metadata:
  name: admin-security-service
  labels:
    run: admin-security-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: admin-security-deploy