apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-admin-deploy
  labels:
    app: web-admin-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-admin-deploy
  template:
    metadata:
      labels:
        app: web-admin-deploy
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      containers:
        - name: web-admin
          image: residencia2020/web-admin-yc:v1.1.0
          ports:
            - containerPort: 80
              protocol: TCP
