apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-volume-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 300Gi
