apiVersion: apps/v1
kind: Deployment
metadata:
  name: onboarding-deploy
  labels:
    app: onboarding-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: onboarding-deploy
  template:
    metadata:
      labels:
        app: onboarding-deploy
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      containers:
        - name: onboarding
          image: residencia2020/onboarding-pr:v1.0.0
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: SERVER_PORT
              value: '8080'
            - name: SPRING_CLOUD_CONFIG_FAILT_FAST
              value: 'true'
            - name: SPRING_PROFILES_ACTIVE
              value: 'pro' 
            - name: SPRING_CLOUD_CONFIG_LABEL
              value: 'master'
