apiVersion: v1
kind: Service
metadata:
  name: onboarding-service
  labels:
    run: onboarding-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: onboarding-deploy