apiVersion: v1
kind: Service
metadata:
  name: web-cust-pr-service
  namespace: default
  labels:
    run: web-cust-pr-service
spec:
  type: ClusterIP
  ports:
  - name: port-cust-pr
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30009
  selector:
    app: web-cust-pr-deploy
