apiVersion: v1
kind: Service
metadata:
  name: web-cust-pr-service
  namespace: default
  labels:
    run: yoconsumo-ent-yc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web-cust-pr-deploy
