apiVersion: v1
kind: Service
metadata:
  name: shopping-car-service
  labels:
    run: shopping-car-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: shopping-car-deploy