apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    run: redis-service
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis-deploy